### ISSUE TITLE
Flash Remoting CFC parameters are case-sensitive

### ISSUE THREAD

**Issue by byron70** [lucee/extension-flex#5]
Receive the following exception, but changing the CFC parameter to `CustNumber` as it is passed in the message results in a successful call. 

This is some additional debugging I have in my compiled version to inspect the message payload

```
raw params
[ASObject(1995395245){CustNumber=12176}]
Object to CFMLObject
ASObject to CFMLObject
Map to CFMLObject
entry
CustNumber=12176
Object to CFMLObject
{CustNumber={12176}}map
```

```
"Severity","ThreadID","Date","Time","Application","Message"
"ERROR","ajp-nio-8009-exec-2","07/10/2018","10:18:42","",";The parameter custNumber to function populateTree is required but was not passed in.;lucee.runtime.exp.ExpressionException: The parameter custNumber to function populateTree is required but was not passed in.
	at lucee.runtime.type.UDFImpl.defineArguments(UDFImpl.java:174)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:355)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:212)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:653)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:575)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:2013)
	at lucee.runtime.ComponentSpecificAccess.callWithNamedValues(ComponentSpecificAccess.java:155)
	at lucee.runtime.ComponentPageImpl.callWDDX(ComponentPageImpl.java:698)
	at lucee.runtime.ComponentPageImpl.call(ComponentPageImpl.java:210)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:901)
	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:823)
	at lucee.runtime.listener.ClassicAppListener._onRequest(ClassicAppListener.java:64)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:45)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2464)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2454)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2427)
	at org.lucee.extension.net.flex.CFMLProxy.invokeBody(CFMLProxy.java:129)
	at org.lucee.extension.net.flex.BlazeDS.invoke(BlazeDS.java:49)
	at org.lucee.extension.net.flex.LuceeAdapter.invoke(LuceeAdapter.java:90)
	at flex.messaging.services.RemotingService.serviceMessage(RemotingService.java:183)
	at flex.messaging.MessageBroker.routeMessageToService(MessageBroker.java:1529)
	at flex.messaging.endpoints.AbstractEndpoint.serviceMessage(AbstractEndpoint.java:907)
	at flex.messaging.endpoints.amf.MessageBrokerFilter.invoke(MessageBrokerFilter.java:121)
	at flex.messaging.endpoints.amf.LegacyFilter.invoke(LegacyFilter.java:158)
	at flex.messaging.endpoints.amf.SessionFilter.invoke(SessionFilter.java:44)
	at flex.messaging.endpoints.amf.BatchProcessFilter.invoke(BatchProcessFilter.java:67)
	at flex.messaging.endpoints.amf.SerializationFilter.invoke(SerializationFilter.java:147)
	at flex.messaging.endpoints.BaseHTTPEndpoint.service(BaseHTTPEndpoint.java:278)
	at flex.messaging.MessageBrokerServlet.service(MessageBrokerServlet.java:322)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:676)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:873)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
"
```

**Comment by byron70** [comment]
With a bit more testing, I've discovered that case sensitivity is only an issue if the CFC argument is tagged as required.

So this is OK, `<CFARGUMENT name="custNumber" type="numeric" default="0">`

While this `<CFARGUMENT name="custNumber" type="numeric" required="yes">` would result in the above exception.
